Traceback (most recent call last):
  File "/Users/tork73/anaconda3/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/tork73/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tork73/anaconda3/lib/python3.11/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tork73/anaconda3/lib/python3.11/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tork73/anaconda3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/tork73/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/tork73/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/tork73/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from IPython.display import Video

Video("coding-chatt.mp4", width=600)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[48], line 3[0m
[1;32m      1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mIPython[39;00m[38;5;21;01m.[39;00m[38;5;21;01mdisplay[39;00m [38;5;28;01mimport[39;00m Video
[0;32m----> 3[0m Video([38;5;124m"[39m[38;5;124mcoding-chatt.mp4[39m[38;5;124m"[39m, width[38;5;241m=[39m[38;5;241m600[39m)

File [0;32m~/anaconda3/lib/python3.11/site-packages/IPython/core/display.py:1162[0m, in [0;36mVideo.__init__[0;34m(self, data, url, filename, embed, mimetype, width, height, html_attributes)[0m
[1;32m   1156[0m [38;5;28;01mif[39;00m data [38;5;129;01mand[39;00m [38;5;129;01mnot[39;00m embed:
[1;32m   1157[0m     msg [38;5;241m=[39m [38;5;124m'[39m[38;5;124m'[39m[38;5;241m.[39mjoin([
[1;32m   1158[0m         [38;5;124m"[39m[38;5;124mTo embed videos, you must pass embed=True [39m[38;5;124m"[39m,
[1;32m   1159[0m         [38;5;124m"[39m[38;5;124m(this may make your notebook files huge)[39m[38;5;130;01m\n[39;00m[38;5;124m"[39m,
[1;32m   1160[0m         [38;5;124m"[39m[38;5;124mConsider passing Video(url=[39m[38;5;124m'[39m[38;5;124m...[39m[38;5;124m'[39m[38;5;124m)[39m[38;5;124m"[39m,
[1;32m   1161[0m     ])
[0;32m-> 1162[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(msg)
[1;32m   1164[0m [38;5;28mself[39m[38;5;241m.[39mmimetype [38;5;241m=[39m mimetype
[1;32m   1165[0m [38;5;28mself[39m[38;5;241m.[39membed [38;5;241m=[39m embed

[0;31mValueError[0m: To embed videos, you must pass embed=True (this may make your notebook files huge)
Consider passing Video(url='...')
ValueError: To embed videos, you must pass embed=True (this may make your notebook files huge)
Consider passing Video(url='...')

